### ISSUE TITLE
ValueError: cannot reshape array of size 324670 into shape (512,256,3,3)

### ISSUE THREAD

**Issue by chrisTopp84** [theAIGuysCode/Object-Detection-API#17]
Hi,
when I'm running `python load_weights.py --weights ./weights/yolov3-tiny.weights --output ./weights/yolov3-tiny.tf --tiny`
on my Jetson Nano (Jetpack 4.3, tensorflow 2.1.0) an error occurs.

**Error:** 

> ValueError: cannot reshape array of size 324670 into shape (512,256,3,3)

Can somebody help me with that? 
Best regards an thanks in advance.

B**elow you will find the complete output after running the python file:**

> (aiguyyolotest1) christopher@ccz:~/aiguyyolotest1/Object-Detection-API$ python load_weights.py --weights ./weights/yolov3-tiny.weights --output ./weights/yolov3-tiny.tf --tiny
> 2020-09-18 08:33:58.451661: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
> 2020-09-18 08:34:03.677829: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
> 2020-09-18 08:34:03.724180: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
> 2020-09-18 08:34:18.304032: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
> 2020-09-18 08:34:18.352799: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:948] ARM64 does not support NUMA - returning NUMA node zero
> 2020-09-18 08:34:18.353007: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
> pciBusID: 0000:00:00.0 name: NVIDIA Tegra X1 computeCapability: 5.3
> coreClock: 0.9216GHz coreCount: 1 deviceMemorySize: 3.87GiB deviceMemoryBandwidth: 23.84GiB/s
> 2020-09-18 08:34:18.353174: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
> 2020-09-18 08:34:18.353300: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
> 2020-09-18 08:34:18.435096: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
> 2020-09-18 08:34:18.543380: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
> 2020-09-18 08:34:18.661994: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
> 2020-09-18 08:34:18.731548: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
> 2020-09-18 08:34:18.732000: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
> 2020-09-18 08:34:18.733151: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:948] ARM64 does not support NUMA - returning NUMA node zero
> 2020-09-18 08:34:18.733627: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:948] ARM64 does not support NUMA - returning NUMA node zero
> 2020-09-18 08:34:18.733735: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
> 2020-09-18 08:34:18.843884: W tensorflow/core/platform/profile_utils/cpu_utils.cc:98] Failed to find bogomips in /proc/cpuinfo; cannot determine CPU frequency
> 2020-09-18 08:34:18.844908: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3ce9c5e0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
> 2020-09-18 08:34:18.844972: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
> 2020-09-18 08:34:18.945611: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:948] ARM64 does not support NUMA - returning NUMA node zero
> 2020-09-18 08:34:18.945924: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3ce01a20 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
> 2020-09-18 08:34:18.945975: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA Tegra X1, Compute Capability 5.3
> 2020-09-18 08:34:18.946674: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:948] ARM64 does not support NUMA - returning NUMA node zero
> 2020-09-18 08:34:18.946802: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
> pciBusID: 0000:00:00.0 name: NVIDIA Tegra X1 computeCapability: 5.3
> coreClock: 0.9216GHz coreCount: 1 deviceMemorySize: 3.87GiB deviceMemoryBandwidth: 23.84GiB/s
> 2020-09-18 08:34:18.946871: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
> 2020-09-18 08:34:18.946920: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
> 2020-09-18 08:34:18.947109: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
> 2020-09-18 08:34:18.947211: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
> 2020-09-18 08:34:18.947296: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
> 2020-09-18 08:34:18.947378: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
> 2020-09-18 08:34:18.947418: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
> 2020-09-18 08:34:18.947742: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:948] ARM64 does not support NUMA - returning NUMA node zero
> 2020-09-18 08:34:18.948078: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:948] ARM64 does not support NUMA - returning NUMA node zero
> 2020-09-18 08:34:18.948156: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
> 2020-09-18 08:34:18.948256: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
> 2020-09-18 08:34:31.465761: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2020-09-18 08:34:31.465973: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0 
> 2020-09-18 08:34:31.466015: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N 
> 2020-09-18 08:34:31.482722: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:948] ARM64 does not support NUMA - returning NUMA node zero
> 2020-09-18 08:34:31.483740: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:948] ARM64 does not support NUMA - returning NUMA node zero
> 2020-09-18 08:34:31.489128: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 279 MB memory) -> physical GPU (device: 0, name: NVIDIA Tegra X1, pci bus id: 0000:00:00.0, compute capability: 5.3)
> Model: "yolov3_tiny"
> __________________________________________________________________________________________________
> Layer (type)                    Output Shape         Param #     Connected to                     
> ==================================================================================================
> input (InputLayer)              [(None, None, None,  0                                            
> __________________________________________________________________________________________________
> yolo_darknet (Model)            ((None, None, None,  6298480     input[0][0]                      
> __________________________________________________________________________________________________
> yolo_conv_0 (Model)             (None, None, None, 2 263168      yolo_darknet[1][1]               
> __________________________________________________________________________________________________
> yolo_conv_1 (Model)             (None, None, None, 3 33280       yolo_conv_0[1][0]                
>                                                                  yolo_darknet[1][0]               
> __________________________________________________________________________________________________
> yolo_output_0 (Model)           (None, None, None, 3 1312511     yolo_conv_0[1][0]                
> __________________________________________________________________________________________________
> yolo_output_1 (Model)           (None, None, None, 3 951295      yolo_conv_1[1][0]                
> __________________________________________________________________________________________________
> yolo_boxes_0 (Lambda)           ((None, None, None,  0           yolo_output_0[1][0]              
> __________________________________________________________________________________________________
> yolo_boxes_1 (Lambda)           ((None, None, None,  0           yolo_output_1[1][0]              
> __________________________________________________________________________________________________
> yolo_nms (Lambda)               ((None, 100, 4), (No 0           yolo_boxes_0[0][0]               
>                                                                  yolo_boxes_0[0][1]               
>                                                                  yolo_boxes_0[0][2]               
>                                                                  yolo_boxes_1[0][0]               
>                                                                  yolo_boxes_1[0][1]               
>                                                                  yolo_boxes_1[0][2]               
> ==================================================================================================
> Total params: 8,858,734
> Trainable params: 8,852,366
> Non-trainable params: 6,368
> __________________________________________________________________________________________________
> I0918 08:34:40.257712 547578310672 load_weights.py:19] model created
> I0918 08:34:40.266925 547578310672 utils.py:47] yolo_darknet/conv2d bn
> I0918 08:34:40.282309 547578310672 utils.py:47] yolo_darknet/conv2d_1 bn
> I0918 08:34:40.295813 547578310672 utils.py:47] yolo_darknet/conv2d_2 bn
> I0918 08:34:40.312008 547578310672 utils.py:47] yolo_darknet/conv2d_3 bn
> I0918 08:34:40.321672 547578310672 utils.py:47] yolo_darknet/conv2d_4 bn
> I0918 08:34:40.345241 547578310672 utils.py:47] yolo_darknet/conv2d_5 bn
> Traceback (most recent call last):
>   File "load_weights.py", line 34, in <module>
>     app.run(main)
>   File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
>     _run_main(main, args)
>   File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
>     sys.exit(main(argv))
>   File "load_weights.py", line 21, in main
>     load_darknet_weights(yolo, FLAGS.weights, FLAGS.tiny)
>   File "/home/christopher/aiguyyolotest1/Object-Detection-API/yolov3_tf2/utils.py", line 68, in load_darknet_weights
>     conv_shape).transpose([2, 3, 1, 0])
> ValueError: cannot reshape array of size 324670 into shape (512,256,3,3)

**Comment by MhdMartini** [comment]
Try specifying the number of classes, e.g.:
`python load_weights.py --num_classes 4`
